### ISSUE TITLE
variabel

### ISSUE THREAD

**Issue by BurhanBudak** [mahmudalhakim/JavaScript-1-Nackademin-2018#6]
https://github.com/mahmudalhakim/JavaScript-1-Nackademin-2018/blob/67be94f88998bbcb6a396db0c1ca31c38442164d/%C3%96vningar/swap.js#L106

Men det är en global variabel.

**Comment by mahmudalhakim** [comment]
Ja, det stämmer. Mycket bra reflektion.
Men denna metod fungerar med alla möjliga variabler för vi btyer plats i en array (referenstyp).
